### ISSUE TITLE
ovs-dpctl-top

### ISSUE THREAD

**Issue by ariksa** [openvswitch/openvswitch.github.io#26]
Hi, I've installed RDO, and I'm trying to work with ovs-dpctl-top.
When I execute ovs-dpctl-top, I get the following error.
```
Traceback (most recent call last):
  File "/usr/bin/ovs-dpctl-top", line 1297, in <module>
    sys.exit(main())
  File "/usr/bin/ovs-dpctl-top", line 1289, in main
    flows_top(args)
  File "/usr/bin/ovs-dpctl-top", line 1198, in flows_top
    flows_read(ihdl, flow_db)
  File "/usr/bin/ovs-dpctl-top", line 600, in flows_read
    flow_db.flow_line_add(line)
  File "/usr/bin/ovs-dpctl-top", line 995, in flow_line_add
    self.flow_event(fields_dict, stats_old_dict, stats_dict)
  File "/usr/bin/ovs-dpctl-top", line 1087, in flow_event
    matches = flow_aggregate(fields_dict, stats_new_dict)
  File "/usr/bin/ovs-dpctl-top", line 583, in flow_aggregate
    field, stats_dict)
  File "/usr/bin/ovs-dpctl-top", line 250, in element_ipv4_get
    element_show = fmt % (field_type, element["src"], element["dst"])
KeyError: 'src'
```

What did I miss?

Thanks

**Comment by blp** [comment]
This is the bug tracker for the openvswitch.org website.  Please report bugs in Open vSwitch on the mailing list, at bugs@openvswitch.org.
